/** @format */

import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import "./globals.css";
// League Spartan

// const inter = Inter({ subsets: ["latin"] });
const league_spartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={league_spartan.className}>{children}</body>
    </html>
  );
}
